# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GvsC_Main', '0002_seating_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_bye',
            field=models.BooleanField(default=False),
        ),
    ]
