# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GvsC_Main', '0003_match_is_bye'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seating',
            old_name='place',
            new_name='result_option',
        ),
        migrations.RemoveField(
            model_name='seating',
            name='seat_number',
        ),
        migrations.RemoveField(
            model_name='seating',
            name='table_number',
        ),
    ]
