# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GvsC_Main', '0004_auto_20160223_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='seating',
            name='winner',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
