# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GvsC_Main', '0005_seating_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seating',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
