# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GvsC_Main', '0006_auto_20160318_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropped', models.BooleanField(default=False)),
                ('dropped_in_round', models.PositiveSmallIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GvsC_Main.Player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GvsC_Main.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentParticipantOpponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('current_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_player', to='GvsC_Main.TournamentParticipant')),
                ('opponent_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_player', to='GvsC_Main.TournamentParticipant')),
            ],
        ),
    ]
