# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GvsC_Main', '0007_tournamentparticipant_tournamentparticipantopponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleplayerseating',
            name='player',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='GvsC_Main.TournamentParticipant'),
        ),
        migrations.AlterField(
            model_name='singleplayertournament',
            name='players',
            field=models.ManyToManyField(blank=True, to='GvsC_Main.TournamentParticipant'),
        ),
    ]
