# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-27 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GvsC_Main', '0008_auto_20160425_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='player',
            name='email_address',
            field=models.EmailField(default='no@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='last', max_length=200),
            preserve_default=False,
        ),
    ]
